### PR TITLE
cpufreq: support kernel 5.1.0

### PR DESCRIPTION
**Pull request by raveit65**
fixes https://github.com/mate-desktop/mate-applets/issues/394
Please test.

### CODE REVIEW

**Comment by raveit65** [comment]
https://src.fedoraproject.org/rpms/mate-applets/c/12e783f5f64c3be1cc78db4f2706e7f3d8a8cc6b?branch=master
builds fine with kernel https://koji.fedoraproject.org/koji/buildinfo?buildID=1263805
Result:
https://koji.fedoraproject.org/koji/taskinfo?taskID=34753138

**Comment by kekePower** [comment]
First test, building it, went really well. Next up is testing.

Thanks a lot for your effort. Really appreciated.

**Comment by lukefromdc** [comment]
Not sure if my test is of any validity. Turns out I get about 3-4MB of linux header files installed into /usr/include/linux always from the last kernel build and make-installed (before packing into a .deb) and these files are in fact for Linux 5.1.0 (based on dates modified and accessed), but I really do NOT know for sure what's going on with them.

**Comment by lukefromdc** [comment]
OK, found my files: they are from linux-libc-dev and are all the linux header type files I have installed

**Comment by lukefromdc** [comment]
Those files are from linux-libc-dev in Debian Unstable, the build fails if they are removed, and they are from kernel 4.19.37-1 as shipped by Debian it seems.
https://github.com/mate-desktop/mate-applets/issues/394#issuecomment-492004220

**Pull request merged**
