### PR TITLE
Fix xml tags in Russian translation

### LINKED ISSUE #388: mateweather doc build segmentation fautl with itstool (With Template)
#### Expected behaviour
Successful Build

#### Actual behaviour
Crash
segmentation fault itstool -m "${mo}" ${d}/C/index.docbook ${d}/C/legal.xml

The problem was pin-point to be within
mate-applets-1.22.0/mateweather/docs/ru/ru.po
replacing ru.po by uk/uk.po (Ukrainian, roughly the same alphabet), make everything compiled.
With a naked eye, the ru.po seems to be quite normal (not a Russian speaking).
I do not believe it is a compilation workbench problem (itstool libraries), as all other foreign documentation (fr,it,zh,zu,etc.) are done without trouble.

#### Steps to reproduce the behaviour
Build (configure + make)

#### MATE general version
1.22.0

#### Package version
1.22.0

#### Linux Distribution
OSUKISS

#### Link to downstream report of your Distribution
I am the distribution builder

### PR DESCRIPTION
**Pull request by rbuj**
closes #388

### CODE REVIEW

**Comment by raveit65** [comment]
IHMO, you need to fix that a transifex.
Otherwise the .po files will be overwritten again by next pull from transifex server.

**Comment by rbuj** [comment]
@raveit65 
I fixed the Russian translation in tx, next I pulled it:
`tx pull -l=ru -f`

**Comment by rbuj** [comment]
XML issues for Russian translation:
```
find . -name ru.po -exec pofilter -t xmltags --progress=none --nofuzzy {} \;
```

**Comment by raveit65** [comment]
Why you didn't a pull on master and all affected branches and commit the result?
I do not get why a PR for a result of a `tx pull` ?

**Comment by rbuj** [comment]
ok, I'm sorry.

**Pull request closed without merging**
