### PR TITLE
ci: add cpupower build dependency to archlinux

### PR DESCRIPTION
**Pull request by yetist**
Now it can found the cpupower library when building:
https://travis-ci.org/mate-desktop/mate-applets/jobs/587805787#L875

### CODE REVIEW

**Comment by raveit65** [comment]
This works, but it doesn't fix real issue described here.
https://github.com/mate-desktop/mate-applets/issues/426

**Comment by raveit65** [comment]
Btw. i am still wondering why archlinux doesn't use kernel-tools package.

**Comment by monsta** [comment]
Ok, and https://github.com/mate-desktop/mate-applets/pull/428 brings back building w/o libcpupower/libcpufreq installed (the applet should use sysfs backend in that case).

**Comment by mhussaincov** [comment]
hi there,
arch linux user here,
could there be a version of the package in the interim that could be
releaced to the archlinux repos?
I relie on the cpufreq applet which currently is not displaying for me?
Majid

On 22/09/2019, raveit65 <notifications@github.com> wrote:
> raveit65 approved this pull request.
>
> Fix building on archlinux.
>
>
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/mate-desktop/mate-applets/pull/427#pullrequestreview-291501148


-- 
kind regards,
Majid Hussain

**Comment by raveit65** [comment]
We don't have control about archlinux. You need to ask archlinux itself.

**Comment by mhussaincov** [comment]
hi there,
how would I go about asking my arch linux install for the updates to
mate-applets package?
confuzed?
would you know the contact for the devs?
thanks for your assistence,
Majid Hussain

On 28/09/2019, raveit65 <notifications@github.com> wrote:
> We don't have control about archlinux. You need to ask archlinux itself.
>
> --
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/mate-desktop/mate-applets/pull/427#issuecomment-536172900


-- 
kind regards,
Majid Hussain

**Pull request merged**
