### PR TITLE
Support git.mk to generate .gitignore

### PR DESCRIPTION
**Pull request by yetist**
`git.mk` can autogenerate `.gitignore` file for autotool-based project, but `Makefile.am` should include it.

How to use:
```bash
$ git config alias.down-git-mk $'!wget https://github.com/behdad/git.mk/raw/master/git.mk'
$ git down-git-mk    # will download git.mk file.
$ make -f git.mk 
$ # please run ./autogen.sh or ./configure to generate Makefile.
$ make gitignore # will generate .gitignore file
$ git status # will see clean output now.
```

### CODE REVIEW

**Comment by muktupavels** [comment]
Why git.mk is not added? Do you expect that everyone will manually download it?

**Comment by lukefromdc** [comment]
I do not know what this does or is used for so someone else will need to test it

**Comment by yetist** [comment]
> Why git.mk is not added? Do you expect that everyone will manually download it?

I want to add git.mk, but it looks like the mate desktop team doesn't like it. Because I found that in mate-session-manager, there should have been git.mk, but it does not exist.
https://github.com/mate-desktop/mate-session-manager/blob/master/Makefile.am#L41

**Comment by raveit65** [comment]
I think it was a personal decision of previous MATE founders not to use such a file in git repos.
Personal i am fine with adding those file.
Thoughts?
@lukefromdc @monsta @vkareh @sc0w

**Comment by lukefromdc** [comment]
I have no idea, as I never build from the same directory that I push to git, always making a copy(which is trivial to do)

**Comment by raveit65** [comment]
@yetist 
Can you add the `git.mk` to PR please.
I don't think it is a big deal , as nobody else did answer to my question.

**Pull request merged**
