### PR TITLE
Fix #372 by using GtkInvisible widget

### LINKED ISSUE #372: Charpick (Character Palette) applet overlapping
Hello! I have a small bug with the Character Palette applet.

#### Expected behaviour
Normal display of buttons when switching them

screenshottraditional
(TraditionalOk desktop theme)

#### Actual behaviour
When switching sets, the buttons overlap each other.

screenshot2
screenshot3
screenshot

#### Steps to reproduce the behaviour
1. Add Character Palette applet to panel
2. Choose one character set
3. Click on any char
4. Choose other character set

This bug appear in all desktop themes (from mate-themes) except TraditionalOk and TraditionalGreen.

#### MATE general version
1.20.3

#### Package version
mate-applets v1.20.2

#### Linux Distribution
ALT Linux Workstation 8.2
Mint 19

### PR DESCRIPTION
**Pull request by balping**
Applied following patches by @muktupavels

* https://gitlab.gnome.org/GNOME/gnome-applets/-/commit/36f313d880aef4df2925a1fce585fa820429d4fd
* https://gitlab.gnome.org/GNOME/gnome-applets/-/commit/19c7ccdc26094988c979fa2ee9ace315acfa9f5e

### CODE REVIEW

**Comment by balping** [comment]
Previous discussion #609 

@muktupavels I tried your patches and the first one solved the issue! The one about calling rebuild from idle didn't have any noticeable effect for me, but I included it nonetheless, I'm sure you had a good reason.

Thanks for your help!

**Review by lukefromdc — COMMENTED** [review]
With this we no longer have the failure to rerender changed images (always an ugly mess...) and the backgrounds behind the characters are rendered correctly. We still get (as in the other PR) a failure in the Yaru themes and BlackMATE of a selected character to stay selected, other MATE themes work fine.

**Comment by balping** [comment]
That should probably be fixed in the themes themselves.

**Comment by lukefromdc** [comment]
Than this is probably fine as-is, themes can be easily fixed and as matters stand the applet can't be easily used. Anyone else going to review it or should we go ahead and merge this?

**Comment by raveit65** [comment]
Can you please update commit header with a short-description-what-the-commit-does and move to the link to commit body?
Something like this
```
 short-description-what-the-commit-does-code

- Fix mate-desktop #372
Applied following patches by Alberts Muktupāvels:

* https://gitlab.gnome.org/GNOME/gnome-applets/-/commit/36f313d880aef4df2925a1fce585fa820429d4fd
* https://gitlab.gnome.org/GNOME/gnome-applets/-/commit/19c7ccdc26094988c979fa2ee9ace315acfa9f5e
```
We don't add links in commit headers here in MATE repos.

**Comment by raveit65** [comment]
I guess the correct `button.flat` css  selector button state is missing in some themes.
Gtk3Inspector:
Bildschirmfoto zu 2021-09-10 17-48-16

Our default theme Blue-Menta and Menta  displays the flat buttons well, with Gtk3-inspector
`.mate-panel-menu-bar #PanelApplet button.flat:checked {}`
See https://github.com/mate-desktop/mate-themes/blob/master/desktop-themes/BlueMenta/gtk-3.0/mate-applications.css#L474

Well, that is definitely a theme issue an can be fixed there.

**Comment by raveit65** [comment]
@blue-devil-93
Can you please take a lool for Yaru themes?

**Comment by blue-devil-93** [comment]
@raveit65
Need to know which class of button flat is affected and also on which
applications this bug des occur. A gif taken with peek or good screenshot.
 I can test with ubuntu 21.04 ,21.10 repo or fedora.

**Comment by raveit65** [comment]
@blue-devil-93
You need to ask @lukefromdc  See comments here

**Comment by raveit65** [comment]
> @raveit65 Need to know which class of button flat is affected and also on which applications this bug des occur. A gif taken with peek or good screenshot. I can test with ubuntu 21.04 ,21.10 repo or fedora.

I posted already css name and class here :) 

https://github.com/mate-desktop/mate-applets/pull/610#issuecomment-917019376
And it is the charpick-applet.

**Comment by blue-devil-93** [comment]
Ok did now understand the bug.
Tomorrow or on sunday ill fix it.
Bug seems to be there in ubuntu 18.04 and later.

>
>

**Comment by balping** [comment]
@raveit65 

> Can you please update commit header with a short-description-what-the-commit-does-in-code and move to the link to commit body?

Done.

**Review by raveit65 — APPROVED** [review]
LGTM

**Comment by blue-devil-93** [comment]
Tried to fix this on Yaru ok and green as an merge request.
.

**Pull request merged**
