### PR TITLE
Fix dependency check of autogen.sh

### LINKED ISSUE #583: autogen.sh doesn't check for autopoint-dependency
#### Expected behaviour

Should notify user of missing dependency `autopoint`.

#### Actual behaviour

`./autogen.sh` fails with error without meaningful message.

#### Steps to reproduce the behaviour

Run `./autogen.sh` without having `autopoint` installed.

#### MATE general version

Current development snapshot.

### PR DESCRIPTION
**Pull request by treysis**
Fixes #583

### CODE REVIEW

**Comment by rbuj** [comment]
Internationalization of packages is optional, so autopoint can't be mandatory.
https://www.gnu.org/software/gettext/manual/html_node/lib_002fgettext_002eh.html

**Comment by rbuj** [comment]
`autopoint` is already checked on `autoreconf ` sentence in `mate-autogen` file

**Comment by treysis** [comment]
But if you just compile mate-applets, shouldn't there be a separate check? Not everyone wants to compile the whole mate desktop suite.

**Comment by rbuj** [comment]
Take a look at the last line of the autogen.sh file. 
```
. mate-autogen
```

**Comment by treysis** [comment]
It fails before that.

**Comment by rbuj** [comment]
> It fails before that.

It's not true. Test: adding -xv in shebang.

**Pull request closed without merging**
