### PR TITLE
multiload: filter-out non-local disks and user mounts

### LINKED ISSUE #171: multiload: permission denied on FUSE filesystems (gvfs mountentries)
Enabling Harddisk monitor causes the journal to get flooded with messages like

```
Dec 22 12:00:36 aaron-desktop org.mate.panel.applet.MultiLoadAppletFactory[2483]: glibtop(c=5008): [WARNING] statvfs '/run/user/42/gvfs' failed: Permission denied
```

Could an exception be added to GetDiskLoad to prevent the method from trying to poll fsusage for FUSE mounts owned by other users?
## GetDiskLoad()

```
multiload/linux-proc.c
GetDiskLoad()
```

```
mountentries = glibtop_get_mountlist (&mountlist, FALSE);
for (i = 0; i < mountlist.number; i++)
{
    glibtop_fsusage fsusage;

    if (strcmp(mountentries[i].type, "smbfs") == 0
        || strcmp(mountentries[i].type, "nfs") == 0
        || strcmp(mountentries[i].type, "cifs") == 0)
        continue;

    glibtop_get_fsusage(&fsusage, mountentries[i].mountdir);
    read += fsusage.read; write += fsusage.write;
}
```
## 

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/29333158-multiload-permission-denied-on-fuse-filesystems-gvfs-mountentries?utm_campaign=plugin&utm_content=tracker%2F517519&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F517519&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by rbuj**
Fix #171

### CODE REVIEW

**Comment by raveit65** [comment]
How can this be tested?

**Comment by rbuj** [comment]
Modified version of [df.c example](https://github.com/GNOME/libgtop/blob/master/examples/df.c):
- Don't show all FS. glibtop_get_mountlist(&buf, **TRUE**) -> glibtop_get_mountlist(&buf, **FALSE**)
- Add devname in print_fsusage
- Remove argv parsing
```C
#include <glibtop.h>
#include <glibtop/fsusage.h>
#include <glibtop/mountlist.h>
#include <stdio.h>

static void print_fsusage(const char *mountpoint, const char *devname)
{
  glibtop_fsusage buf;

  enum { SIZE, USED, FREE, AVAIL, READ, WRITE, MAX };
  char **a = g_new0(char*, MAX);

  glibtop_get_fsusage(&buf, mountpoint);

#define I(X) a[(X)]
  I(SIZE)  = g_format_size_full(buf.blocks * buf.block_size, G_FORMAT_SIZE_IEC_UNITS);
  I(USED)  = g_format_size_full((buf.blocks - buf.bavail)  * buf.block_size, G_FORMAT_SIZE_IEC_UNITS);
  I(FREE)  = g_format_size_full(buf.bfree * buf.block_size, G_FORMAT_SIZE_IEC_UNITS);
  I(AVAIL) = g_format_size_full(buf.bavail * buf.block_size, G_FORMAT_SIZE_IEC_UNITS);
  I(READ)  = g_format_size_full(buf.read, G_FORMAT_SIZE_IEC_UNITS);
  I(WRITE) = g_format_size_full(buf.write, G_FORMAT_SIZE_IEC_UNITS);

  printf("%#7x %10s %10s %10s %10s %5.1f%% %10s %10s %8lu %8lu %s %s\n",
    (unsigned)buf.flags,
    I(SIZE),
    I(USED),
    I(FREE),
    I(AVAIL),
    (buf.blocks - buf.bavail) * 100.0 / (buf.blocks ? buf.blocks : 1.0),
    I(READ),
    I(WRITE),
    (unsigned long)buf.files,
    (unsigned long)buf.ffree,
    mountpoint,
    devname
    );

  g_strfreev(a);
}

int main(int argc, char **argv)
{
  glibtop_init();

  printf("%-6s %10s %10s %10s %10s %5s %10s %10s %10s %10s %s %s\n",
	 "(flags)", "Size", "Used", "Free", "Avail", "Use%", "Read", "Write", "Files", "Files Free", "Mountpoint", "Device");

  glibtop_mountlist buf;
  glibtop_mountentry *entries = glibtop_get_mountlist(&buf, FALSE);
  entries = glibtop_get_mountlist(&buf, FALSE);
  size_t i;
  for(i = 0; i < buf.number; ++i)
  {
    print_fsusage(entries[i].mountdir, entries[i].devname);
  }

  g_free(entries);
  glibtop_close();
  return 0;
}
```
build:
```shell
gcc -o df `pkg-config --cflags --libs libgtop-2.0` -Wall df.c
```
Output:
```shell
$ ./df
(flags)       Size       Used       Free      Avail  Use%       Read      Write      Files Files Free Mountpoint Device
   0x3f  36.7 GiB  10.4 GiB  28.2 GiB  26.3 GiB  28.4%    0 bytes    0 bytes  2465792  2203836 / /dev/mapper/fedora_localhost--live-root
   0x3f  17.9 GiB   1.2 GiB  17.7 GiB  16.7 GiB   6.8%    0 bytes    0 bytes  1204224  1197603 /home /dev/mapper/fedora_localhost--live-home
   0xff 975.9 MiB 284.3 MiB 758.8 MiB 691.6 MiB  29.1%  10.2 KiB   88 bytes    65536    65120 /boot /dev/sda1
   0x3f    0 bytes    0 bytes    0 bytes    0 bytes   0.0%    0 bytes    0 bytes        0        0 /run/user/1000/gvfs gvfsd-fuse
```
Filtered mountentries:
```C
    if (strstr (entries[i].devname, "/dev/") == NULL)
      continue;

    if (strstr (entries[i].mountdir, "/media/") != NULL)
      continue;
```
df.c source:
```C
#include <glibtop.h>
#include <glibtop/fsusage.h>
#include <glibtop/mountlist.h>
#include <stdio.h>

static void print_fsusage(const char *mountpoint, const char *devname)
{
  glibtop_fsusage buf;

  enum { SIZE, USED, FREE, AVAIL, READ, WRITE, MAX };
  char **a = g_new0(char*, MAX);

  glibtop_get_fsusage(&buf, mountpoint);

#define I(X) a[(X)]
  I(SIZE)  = g_format_size_full(buf.blocks * buf.block_size, G_FORMAT_SIZE_IEC_UNITS);
  I(USED)  = g_format_size_full((buf.blocks - buf.bavail)  * buf.block_size, G_FORMAT_SIZE_IEC_UNITS);
  I(FREE)  = g_format_size_full(buf.bfree * buf.block_size, G_FORMAT_SIZE_IEC_UNITS);
  I(AVAIL) = g_format_size_full(buf.bavail * buf.block_size, G_FORMAT_SIZE_IEC_UNITS);
  I(READ)  = g_format_size_full(buf.read, G_FORMAT_SIZE_IEC_UNITS);
  I(WRITE) = g_format_size_full(buf.write, G_FORMAT_SIZE_IEC_UNITS);

  printf("%#7x %10s %10s %10s %10s %5.1f%% %10s %10s %8lu %8lu %s %s\n",
    (unsigned)buf.flags,
    I(SIZE),
    I(USED),
    I(FREE),
    I(AVAIL),
    (buf.blocks - buf.bavail) * 100.0 / (buf.blocks ? buf.blocks : 1.0),
    I(READ),
    I(WRITE),
    (unsigned long)buf.files,
    (unsigned long)buf.ffree,
    mountpoint,
    devname
    );

  g_strfreev(a);
}

int main(int argc, char **argv)
{
  glibtop_init();

  printf("%-6s %10s %10s %10s %10s %5s %10s %10s %10s %10s %s %s\n",
	 "(flags)", "Size", "Used", "Free", "Avail", "Use%", "Read", "Write", "Files", "Files Free", "Mountpoint", "Device");

  glibtop_mountlist buf;
  glibtop_mountentry *entries = glibtop_get_mountlist(&buf, FALSE);
  entries = glibtop_get_mountlist(&buf, FALSE);
  size_t i;
  for(i = 0; i < buf.number; ++i)
  {
    if (strstr (entries[i].devname, "/dev/") == NULL)
      continue;

    if (strstr (entries[i].mountdir, "/media/") != NULL)
      continue;

    print_fsusage(entries[i].mountdir, entries[i].devname);
  }

  g_free(entries);
  glibtop_close();
  return 0;
}
```
Output:
```shell
$ ./df
(flags)       Size       Used       Free      Avail  Use%       Read      Write      Files Files Free Mountpoint Device
   0x3f  36.7 GiB  10.4 GiB  28.2 GiB  26.3 GiB  28.4%    0 bytes    0 bytes  2465792  2203836 / /dev/mapper/fedora_localhost--live-root
   0x3f  17.9 GiB   1.2 GiB  17.7 GiB  16.7 GiB   6.8%    0 bytes    0 bytes  1204224  1197603 /home /dev/mapper/fedora_localhost--live-home
   0xff 975.9 MiB 284.3 MiB 758.8 MiB 691.6 MiB  29.1%  10.2 KiB   88 bytes    65536    65120 /boot /dev/sda1
```
The mountentry `/run/user/1000/gvfs` is ignored because the device name **gvfsd-fuse** doesn't contain **/dev/** substring.

**Comment by raveit65** [comment]
Hmm, i have a lot of local partitions mounted under /media/ in my /etc/fstab.
I do not get why this local mounts should be ignored only because people use docker images.
I am using VMs for testing software.

**Comment by raveit65** [comment]
The applet builds and runs fine. Maybe it is possible to add a gsettings key for this? 
I can imagine that some users like to monitor the disk-activity of all mounts on a bare metal system?
Well, personal i don't care very much about and i can live with new behavior.

**Pull request merged**
