### PR TITLE
multiload: Do not label the tooltip intuitively

### PR DESCRIPTION
**Pull request by rbuj**

### CODE REVIEW

**Comment by raveit65** [comment]
Too much open reviews!

**Comment by raveit65** [comment]
Well, no need to close them, but i would really prefer to focus our work on existing open PRs for the moment.

**Comment by raveit65** [comment]
@rbuj 
Maybe you have some free time to work on this issue?
https://github.com/mate-desktop/mate-applets/issues/400
The day will come that wireless-tools will be dropped from kernel.
I think this notification was from a fedora kernel dev.

**Comment by rbuj** [comment]
@raveit65 I tried to run this simple monitor without much luck as it causes the wireless connection to be continuously lost.

https://github.com/Alamot/code-snippets/blob/master/nl80211_info/nl80211_info.c

```
$ sudo dnf install -y libnl3-devel
$ make
$ ./nl80211_info
Interface: wlp3s0b1 | signal: 41 dB | txrate: 115.6 MBit/s
Interface: wlp3s0b1 | signal: 41 dB | txrate: 117.0 MBit/s
Interface: wlp3s0b1 | signal: 41 dB | txrate: 117.0 MBit/s
Interface: wlp3s0b1 | signal: 40 dB | txrate: 130.0 MBit/s
Interface: wlp3s0b1 | signal: 41 dB | txrate: 130.0 MBit/s
^C
Exiting gracefully... OK
```

**Comment by rbuj** [comment]
@raveit65 iw doesn't seem to break the connection, I'll take a look how it works as It also uses nl80211... 
```
$ while true; do iw dev wlp3s0b1 link; sleep 1; done
```

**Comment by raveit65** [comment]
Thanks a lot .

**Pull request closed without merging**
