### PR TITLE
WIP netspeed: remove ipv4 routing check

### PR DESCRIPTION
**Pull request by rbuj**

### CODE REVIEW

**Comment by vkareh** [comment]
What's the purpose of this? With your branch I lose a lot of information from my netspeed window:

* `master`:
Screenshot at 2020-12-22 08-44-13

* `pull/576`
Screenshot at 2020-12-22 08-44-43

**Comment by rbuj** [comment]
The `get_default_route` was added for selecting an interface with a gateway on startup. It's part of the legacy and It makes a lot of unnecessary calls to pull current device info. The network graph data is collected from network status snapshots, and these are taken periodically, so there is no need to add extra snapshot on each iteration. I'll check it on baremetal for testing a wireless connection.

**Comment by rbuj** [comment]
@vkareh It worked fine on baremetal:

Screenshot at 2020-12-22 20-51-13

**Comment by vkareh** [comment]
My tests are all in baremetal. This still doesn't work for my default/wireless device.

**Comment by vkareh** [comment]
wait... poking around at it, the wireless device works, but it's no longer the default. For some reason your patch changes what my default interface is... ???

**Comment by rbuj** [comment]
Ok, the code is still used for setting the Default interface name. However, it only takes into account the ipv4 routing table.

**Pull request closed without merging**
