### PR TITLE
build: Use WARN_CFLAGS variable

### PR DESCRIPTION
**Pull request by rbuj**
Test:
```
$ ./autogen.sh --prefix=/usr --enable-compile-warnings=maximum && make V=1
```

### CODE REVIEW

**Comment by raveit65** [comment]
@rbuj 
I think we can remove the --enable-more-warnings flag too, please.
https://github.com/mate-desktop/mate-applets/blob/master/configure.ac#L47

**Comment by rbuj** [comment]
@raveit65 done

**Comment by raveit65** [comment]
Warn_Cflags are there now.
https://travis-ci.org/github/mate-desktop/mate-applets/jobs/672428072#L1229
```
Compiler warnings:             -Wall -Wmissing-prototypes -Wbad-function-cast -Wcast-align -Wextra -Wno-unused-parameter -Wformat-nonliteral -Wmissing-declarations -Wmissing-field-initializers -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wno-sign-compare
```
Eg. charpick-applet. https://travis-ci.org/github/mate-desktop/mate-applets/jobs/672428072#L2175

**Comment by sc0w** [comment]
one question:

we need `--enable-compile-warnings=maximum` with `autogen.sh` at travis?

I noticed we have it into other repositories

**Comment by raveit65** [comment]
@sc0w 
no, `make` isn`t executed after autogen.sh, see build logs.
After autogen.sh, `configure ---enable-compile-warnings=maximum` is called by `scan-build`, which is the important place to add it.
So, no need to call it first with autogen.sh.
This double call can be safely removed in other repos.

**Comment by sc0w** [comment]
reviewing the logs...

comparing the travis log of this PR and the travis log of commit https://github.com/mate-desktop/mate-applets/commit/82804f22bec0aa07e298e1c53a1f82f3b4000bde 

I see new warnings in the logs, no problem, the expected.

I see less warnings in the logs: `-Wunused-parameter` (the expected since the commit https://github.com/mate-desktop/mate-common/commit/2f5ddbbca624f5be80e5463a85616f18df26c643) and `-Wsign-compare`

Why we can't see `-Wsign-compare` warnings?

https://gcc.gnu.org/onlinedocs/gcc-6.2.0/gcc/Warning-Options.html says `-Wsign-compare` is included in `-Wextra` and I see it in mate-common warning flags.

**Comment by rbuj** [comment]
@sc0w this indicator is explicitly disabled (`-Wno-sign-compare`) at:

https://github.com/mate-desktop/mate-common/blob/36fb1b59ef79aafc810e1790cfc513cdf3633d0b/macros/mate-compiler-flags.m4#L52

**Comment by raveit65** [comment]
`Wno-sign-compare` is used in logs
```
Compiler warnings:             -Wall -Wmissing-prototypes -Wbad-function-cast -Wcast-align -Wextra -Wno-unused-parameter -Wformat-nonliteral -Wmissing-declarations -Wmissing-field-initializers -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wno-sign-compare
```
at https://travis-ci.org/github/mate-desktop/mate-applets/jobs/672428185#L1288

**Comment by raveit65** [comment]
Looks this was an old gnome setting, see https://github.com/mate-desktop/mate-common/commit/d404d8b45c48c912ce80d683d4406018779b52d3#diff-82a0ba019db05f441daaddedbb505c20L52
No idea why they had disable the warning.
In general we can update warn_cflags in mate-common when there is a good reason to use this warn_cflag, and we can expect that someone will fix them.
On the other hand we have currently a lot of warnings in build logs to fix :)

**Comment by sc0w** [comment]
@rbuj `"--enable-compile-warnings=maximum"` don't work in `python-caja`

please, can you take a look?

**Comment by rbuj** [comment]
@sc0w PR https://github.com/mate-desktop/python-caja/pull/57

**Pull request merged**
