### PR TITLE
multiload: Display the percentage used accurately on tooltip

### PR DESCRIPTION
**Pull request by rbuj**

### CODE REVIEW

**Comment by raveit65** [comment]
Now , i 've only one value in tooltip (mem use).
I think we should first finished discussion about what we want to display in other PRs, before we update tooltips.

**Comment by rbuj** [comment]
It needs to be reworked after #489. It blocks #493

**Comment by rbuj** [comment]
I'm done, it's ready for review.

**Comment by raveit65** [comment]
I don't have any graph with this PR.
With mate-applets-1.25.0
multiload-1 25 0
With master and https://github.com/mate-desktop/mate-applets/pull/489
multiload-1 25 0-master
With master + https://github.com/mate-desktop/mate-applets/pull/489 and this PR
multiload-1 25 0-master+PR

**Comment by rbuj** [comment]
I think it's fixed now

**Comment by raveit65** [comment]
This is working now :)
multiload-new-good

**Pull request merged**
