### PR TITLE
[ci] enable clang analyzer

### PR DESCRIPTION
**Pull request by yetist**

### CODE REVIEW

**Comment by sc0w** [comment]
it doesn't work:

**Comment by raveit65** [comment]
I enabled GitHub Pages, should be work now.

**Comment by raveit65** [comment]
I got this email warning again.
```
From - Wed Apr 10 23:21:01 2019
<cut>
From: GitHub <support@github.com>
To: raveit65 <mate@raveit.de>
<cut>

The page build completed successfully, but returned the following warning for the `gh-pages` branch:

The CNAME `mate-applets.mate-desktop.dev` is already taken. Check out https://help.github.com/articles/troubleshooting-custom-domains/#cname-already-taken for more information.

For information on troubleshooting Jekyll see:

  https://help.github.com/articles/troubleshooting-jekyll-builds

If you have any questions you can contact us by replying to this email.
```

**Comment by yetist** [comment]
@raveit65 

I test it with my forked repo, now I deleted the `CNAME` file from that, it will be ok soon.
https://github.com/yetist/mate-applets/commits/gh-pages

**Pull request merged**
