### PR TITLE
mateweather: set values before connecting signals on preferences dialog

### PR DESCRIPTION
**Pull request by rbuj**

### CODE REVIEW

**Review by vkareh — APPROVED** [review]
LGTM

**Comment by raveit65** [comment]
Most changes are code-style fixes. 
Ok, in this case the real changes are easy find after a long scrolling through the commit.
Can you add to commit body that you fixed also code-formatting please?

**Comment by rbuj** [comment]
@raveit65 done

**Review by raveit65 — APPROVED** [review]
LGTM.

**Pull request merged**
