### PR TITLE
timerapplet: Allow reseting timer when inactive

### LINKED ISSUE #337: Timer applet shouldn't display Finished
Hello,

I think when the Timer applet is finished it should reset to displaying its name instead of displaying 'Finished' until eternity. I have multiple timers related to different activities on my panel and after I used them once I can't see their given name anymore, which makes it hard to tell which one is which. I see no reason to display the text 'Finished' forever after you used it once.

Thank you!
Victoria

### PR DESCRIPTION
**Pull request by vkareh**
Fixes #337

### CODE REVIEW

**Comment by vkareh** [comment]
@raveit65 - agreed, the reporter wanted an auto-reset, but I played with that and it was very easy to miss. Another option that worked well enough was that when the timer is Finished, a click on the applet will automatically reset it. I can add that very easily if we want it, but it changes the behavior, so adding a simple action seems harmless for now.

**Comment by raveit65** [comment]
I you like to add an click-on-applet function than i would prefer start/stop the timer.
This is is what i always try to do if i see that applet in panel :)

**Comment by raveit65** [comment]
Btw. is it not possible the display 'Finished timer-name' in panel instead of only 'Finished'?

**Comment by vkareh** [comment]
@raveit65 - true, these are good changes. Here's what I have in mind:

* When timer is inactive, display timer name. On click, start timer.
* When timer is active, display count-down. On click, pause timer.
* When timer is paused, display count-down and pause icon. On click, continue timer.
* When timer is finished, display "Finished %timerName%". On click, reset timer.

@nemkin - do you have opinions on these changes?

**Comment by nemkin** [comment]
This solution sounds good! Thank you! :)

**Comment by vkareh** [comment]
@raveit65 - I've updated this commit to add click interactions with the timer. Please review/test

**Pull request merged**
