### PR TITLE
cpufreq: -1 indicates error obtaining max frequency

### PR DESCRIPTION
**Pull request by rbuj**
Test: Add cpufreq-monitor-applet on a VM.

https://github.com/mate-desktop/mate-applets/blob/ca4a3b697836a99590c1e81a0b263588609b647c/cpufreq/src/cpufreq-monitor-libcpufreq.c#L73-L80

### CODE REVIEW

**Comment by raveit65** [comment]
Are you sure with using `-1` for `gint minimum`?
https://developer.gnome.org/gobject/unstable/gobject-Standard-Parameter-and-Value-Types.html#g-param-spec-int

**Comment by rbuj** [comment]
Yes. Integers can also be negative, in that case -1 indicates an error.

**Comment by raveit65** [comment]
The only different i saw when using the applet in VM is that the applet displays directly without resizing the panel.
This is needed with current master here.
Is this the expected progress?

**Comment by rbuj** [comment]
```
$ G_MESSAGES_DEBUG=all /usr/libexec/mate-cpufreq-applet 
<cut>
(mate-cpufreq-applet:1697): GLib-GObject-WARNING **: 17:45:21.876: value "-1" of type 'gint' is invalid or out of range for property 'max-frequency' of type 'gint'
<cut>
```

**Comment by raveit65** [comment]
Ok, got it.
Without PR
```
[rave@f32 ~]$ /usr/libexec/mate-applets/mate-cpufreq-applet 

** (mate-cpufreq-applet:4759): WARNING **: 18:32:15.803: Error getting CPUINFO_MAX


(mate-cpufreq-applet:4759): GLib-GObject-WARNING **: 18:32:15.803: value "-1" of type 'gint' is invalid or out of range for property 'max-frequency' of type 'gint'
```
but the applet won't displayed.
With this PR
```
[rave@f32 ~]$ /usr/libexec/mate-applets/mate-cpufreq-applet 

** (mate-cpufreq-applet:5300): WARNING **: 18:33:25.357: Error getting CPUINFO_MAX
```
and the applet displays well.
Nice :)

**Pull request merged**
