### PR TITLE
fix build with kernel-4.7

### PR DESCRIPTION
**Pull request by leigh123linux**
Should fix https://github.com/mate-desktop/mate-applets/issues/193

### CODE REVIEW

**Comment by raveit65** [comment]
PR works fine with building against kernel 4.6 and latest 4.7.0.rc2
@monsta @flexiondotorg 
Do we need a require for kernel-headers in configure?
For fedora build system this isn't needed, it is always there.
But i don't know the situation in debian & co and others.

**Comment by leigh123linux** [comment]
looking at the existing headers it already requires it to build

```
$ rpm -qf /usr/include/cpufreq.h
kernel-headers-4.6.2-1.fc24.x86_64
kernel-tools-libs-devel-4.5.5-300.fc24.x86_64
```

**Comment by monsta** [comment]
Did you guys test this with ```--with-cpufreq-lib=cpufreq``` option as well?

**Comment by leigh123linux** [comment]
@monsta I'm not able to test that as /usr/lib/libcpufreq.so and /usr/lib64/libcpufreq.so don't exist on fedora.

```
libtool: link: gcc -g -O2 -Wl,-z -Wl,now -o mate-cpufreq-selector cpufreq-selector.o cpufreq-selector-sysfs.o cpufreq-selector-procfs.o cpufreq-selector-libcpufreq.o cpufreq-selector-service.o cpufreq-selector-factory.o main.o  -lcpufreq -lpolkit-gobject-1 -lgio-2.0 -ldbus-glib-1 -ldbus-1 -lgobject-2.0 -lglib-2.0
/usr/bin/ld: cannot find -lcpufreq
```

I don't expect any issues if the distro has libcpufreq.so installed

http://packages.ubuntu.com/precise/amd64/libcpufreq-dev/filelist

**Comment by monsta** [comment]
@flexiondotorg: I think we need to keep an eye on this for future Debian/Ubuntu releases...

**Comment by raveit65** [comment]
@monsta same for me, i can't test this in fedora
For the record, this select only the current kernel during build time.
This means if your distro switch to kernel-4.7 you need to rebuild the package.
And it does not change the function in runtime, ie. if a user or admin use a lower kernel version.

**Pull request merged**
