### PR TITLE
accessx-status: improve code-style

### PR DESCRIPTION
**Pull request by raveit65**
- tab to spaces
- fix indents
- shorten lines

### CODE REVIEW

**Review by rbuj — COMMENTED** [review]
In some lines a space is missing between the name of the function and the opening parenthesis.

Test:
```
$ grep '[A-Za-z](' accessx-status/src/applet.c
```

**Comment by raveit65** [comment]
This was previous codes-style in this document. First i wanted avoid to change that.
But Ok , it's a rewrite,  i will change it. :)

**Comment by raveit65** [comment]
@rbuj 
I'd like to shorten more.
This i know
```
static gboolean accessx_status_applet_xkb_select(AccessxStatusApplet* sapplet) {}
-->
static gboolean
accessx_status_applet_xkb_select(AccessxStatusApplet* sapplet) {}
```
But here i am not sure.
```
static XkbDescPtr accessx_status_applet_get_xkb_desc(AccessxStatusApplet* sapplet) {}
--> 
static XkbDescPtr
accessx_status_applet_get_xkb_desc(AccessxStatusApplet* sapplet) {}
```
Is this fine ^^^ ?

**Comment by rbuj** [comment]
yes, to make it easier to read the code, the data type returned by the function and the name are splitted into two lines, otherwise the line is too long and difficult to read.
```diff
diff --git a/accessx-status/src/applet.c b/accessx-status/src/applet.c
index e2f38ca8..05f39c49 100644
--- a/accessx-status/src/applet.c
+++ b/accessx-status/src/applet.c
@@ -293,7 +293,8 @@ static gboolean accessx_status_applet_xkb_select(AccessxStatusApplet* sapplet)
     return retval;
 }
 
-static void accessx_status_applet_init_modifiers(AccessxStatusApplet* sapplet)
+static void
+accessx_status_applet_init_modifiers (AccessxStatusApplet *sapplet)
 {
     unsigned int hyper_mask, super_mask, alt_gr_mask;
```

**Comment by raveit65** [comment]
Yes, same here? 
```
static XkbDescPtr accessx_status_applet_get_xkb_desc(AccessxStatusApplet* sapplet) {}
--> 
static XkbDescPtr
accessx_status_applet_get_xkb_desc(AccessxStatusApplet* sapplet) {}

```

**Comment by rbuj** [comment]
yes, [XkbDescPtr](https://github.com/freedesktop/xorg-libX11/blob/d127217f26df1bf7566c1f372d8b5329a06754ea/specs/XKB/ch06.xml#L15)  is a struct.

**Comment by raveit65** [comment]
PR is updated.

**Review by rbuj — APPROVED** [review]
It makes easier to read the code

**Pull request merged**
