### PR TITLE
Mateweather: suncalc_timeout_cb randomly gets called multiple times (#231)

### PR DESCRIPTION
**Pull request by ZeGentzy**
This causes notification spam (if they are enabled) according to: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=823790

A solution is to simply not update on sunrise/sunset (why would you anyways?), here is a patch which does this: https://bugs.debian.org/cgi-bin/bugreport.cgi?att=1;bug=823790;filename=bug823790.patch;msg=40
(Issue #231)

### CODE REVIEW

**Comment by raveit65** [comment]
First, i like to reproduce the issue with normal 1.18.0 build.
Giving exactly informations **here** how to trigger the issue in 1-2 sentences won't hurt,
to avoid spending rare time for searching infos in other huge reports.
Thank you.
At the moment i switched to updating weather infos to 5 mins, but the issue can only be seen 2 times a day during sunset/sunrise?
Well, personal i use the weather part from clock applet so i never known about this notifications.
I don't think that i need weather notifications in general ;-)

**Comment by raveit65** [comment]
I can trigger the issue always if i start or stop a virtual machine in graphical mode.
I am using virtual-manager with qemu-kvm.
Ok, now i can test if your fix helps.

**Comment by raveit65** [comment]
I got build issues https://paste.fedoraproject.org/paste/9oH~cmdxtXKEZSA1x-oMr15M1UNdIGYhyRLivL9gydE=/

**Comment by raveit65** [comment]
```
mateweather-applet.c: In function 'applet_destroy':
mateweather-applet.c:298:20: error: 'MateWeatherApplet {aka struct _MateWeatherApplet}' has no member named 'suncalc_timeout_tag'; did you mean 'timeout_tag'?
     if (gw_applet->suncalc_timeout_tag > 0) {
                    ^~~~~~~~~~~~~~~~~~~
                    timeout_tag
mateweather-applet.c:299:35: error: 'MateWeatherApplet {aka struct _MateWeatherApplet}' has no member named 'suncalc_timeout_tag'; did you mean 'timeout_tag'?
        g_source_remove(gw_applet->suncalc_timeout_tag);
                                   ^~~~~~~~~~~~~~~~~~~
                                   timeout_tag
mateweather-applet.c:300:19: error: 'MateWeatherApplet {aka struct _MateWeatherApplet}' has no member named 'suncalc_timeout_tag'; did you mean 'timeout_tag'?
        gw_applet->suncalc_timeout_tag = 0;
                   ^~~~~~~~~~~~~~~~~~~
                   timeout_tag
mateweather-applet.c: In function 'mateweather_applet_create':
mateweather-applet.c:343:5: warning: 'gtk_alignment_new' is deprecated [-Wdeprecated-declarations]
     gw_applet->container = gtk_alignment_new (0.5, 0.5, 0, 0);
     ^~~~~~~~~
In file included from /usr/include/gtk-3.0/gtk/gtk.h:251:0,
                 from /usr/include/mate-panel-4.0/libmate-panel-applet/mate-panel-applet.h:29,
                 from mateweather-applet.c:25:
/usr/include/gtk-3.0/gtk/deprecated/gtkalignment.h:79:12: note: declared here
 GtkWidget* gtk_alignment_new        (gfloat             xalign,
            ^~~~~~~~~~~~~~~~~
mateweather-applet.c:367:5: warning: 'gtk_action_group_new' is deprecated [-Wdeprecated-declarations]
     action_group = gtk_action_group_new ("MateWeather Applet Actions");
     ^~~~~~~~~~~~
In file included from /usr/include/gtk-3.0/gtk/gtk.h:250:0,
                 from /usr/include/mate-panel-4.0/libmate-panel-applet/mate-panel-applet.h:29,
                 from mateweather-applet.c:25:
/usr/include/gtk-3.0/gtk/deprecated/gtkactiongroup.h:175:17: note: declared here
 GtkActionGroup *gtk_action_group_new                     (const gchar                *name);
                 ^~~~~~~~~~~~~~~~~~~~
mateweather-applet.c:368:5: warning: 'gtk_action_group_set_translation_domain' is deprecated [-Wdeprecated-declarations]
     gtk_action_group_set_translation_domain (action_group, GETTEXT_PACKAGE);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/gtk-3.0/gtk/gtk.h:250:0,
                 from /usr/include/mate-panel-4.0/libmate-panel-applet/mate-panel-applet.h:29,
                 from mateweather-applet.c:25:
/usr/include/gtk-3.0/gtk/deprecated/gtkactiongroup.h:252:17: note: declared here
 void            gtk_action_group_set_translation_domain  (GtkActionGroup             *action_group,
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
mateweather-applet.c:369:5: warning: 'gtk_action_group_add_actions' is deprecated [-Wdeprecated-declarations]
     gtk_action_group_add_actions (action_group,
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/gtk-3.0/gtk/gtk.h:250:0,
                 from /usr/include/mate-panel-4.0/libmate-panel-applet/mate-panel-applet.h:29,
                 from mateweather-applet.c:25:
/usr/include/gtk-3.0/gtk/deprecated/gtkactiongroup.h:210:17: note: declared here
 void            gtk_action_group_add_actions             (GtkActionGroup             *action_group,
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
mateweather-applet.c:381:6: warning: 'gtk_action_group_get_action' is deprecated [-Wdeprecated-declarations]
      action = gtk_action_group_get_action (action_group, "Props");
      ^~~~~~
In file included from /usr/include/gtk-3.0/gtk/gtk.h:250:0,
                 from /usr/include/mate-panel-4.0/libmate-panel-applet/mate-panel-applet.h:29,
                 from mateweather-applet.c:25:
/usr/include/gtk-3.0/gtk/deprecated/gtkactiongroup.h:195:17: note: declared here
 GtkAction      *gtk_action_group_get_action              (GtkActionGroup             *action_group,
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~
mateweather-applet.c:382:6: warning: 'gtk_action_set_visible' is deprecated [-Wdeprecated-declarations]
      gtk_action_set_visible (action, FALSE);
      ^~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/gtk-3.0/gtk/deprecated/gtkactivatable.h:25:0,
                 from /usr/include/gtk-3.0/gtk/gtk.h:248,
                 from /usr/include/mate-panel-4.0/libmate-panel-applet/mate-panel-applet.h:29,
                 from mateweather-applet.c:25:
/usr/include/gtk-3.0/gtk/deprecated/gtkaction.h:116:14: note: declared here
 void         gtk_action_set_visible            (GtkAction     *action,
              ^~~~~~~~~~~~~~~~~~~~~~
mateweather-applet.c: In function 'update_finish':
mateweather-applet.c:424:24: error: 'MateWeatherApplet {aka struct _MateWeatherApplet}' has no member named 'suncalc_timeout_tag'; did you mean 'timeout_tag'?
             gw_applet->suncalc_timeout_tag =
                        ^~~~~~~~~~~~~~~~~~~
                        timeout_tag
mateweather-applet.c:426:33: error: 'suncalc_timeout_cb' undeclared (first use in this function); did you mean 'timeout_cb'?
                                 suncalc_timeout_cb, gw_applet);
                                 ^~~~~~~~~~~~~~~~~~
                                 timeout_cb
mateweather-applet.c:426:33: note: each undeclared identifier is reported only once for each function it appears in
make[3]: Leaving directory '/builddir/build/BUILD/mate-applets-1.18.0/mateweather'
make[2]: Leaving directory '/builddir/build/BUILD/mate-applets-1.18.0/mateweather'
make[1]: Leaving directory '/builddir/build/BUILD/mate-applets-1.18.0'


RPM build errors:
make[3]: *** [Makefile:626: mateweather-applet.o] Error 1
make[2]: *** [Makefile:718: all-recursive] Error 1
make[1]: *** [Makefile:567: all-recursive] Error 1
make: *** [Makefile:499: all] Error 2
```

**Comment by sbalneav** [comment]
Following patch fixes build issue:

[fix_build_issue.patch.txt](https://github.com/mate-desktop/mate-applets/files/868471/fix_build_issue.patch.txt)

**Comment by sbalneav** [comment]
Try this patch
[fix_build_issue1.patch.txt](https://github.com/mate-desktop/mate-applets/files/868502/fix_build_issue1.patch.txt)

**Comment by raveit65** [comment]
This PR does not really help to fix the tripple notificatons here.

**Comment by raveit65** [comment]
fixed with
https://github.com/mate-desktop/libmateweather/commit/97326e615fffaef92669dbe82c8955c2c2e2edda
https://github.com/mate-desktop/libmateweather/commit/c307e7c9ee89e4ac17cc2bb2aa1e245d766cbc5e
https://github.com/mate-desktop/mate-applets/commit/109a7fa77bb4745524eca8a0735b210b55b81fe0
https://github.com/mate-desktop/mate-applets/commit/dc71847a5490abad09ef0b4955b5461d8e66ed3f

Fixed libmateweather-1.19.1 and mate-applets-1.19.0 are released.

**Pull request closed without merging**
