### PR TITLE
multiload: Use common subdirs - src, data

### PR DESCRIPTION
**Pull request by rbuj**

### CODE REVIEW

**Comment by rbuj** [comment]
It only fixes a merge conflict.

**Review by vkareh — COMMENTED** [review]
I'm getting this error:
```
** (mate-multiload-applet:174034): WARNING **: 14:38:13.748: Failed to open file “multiload-applet-menu.xml”: No such file or directory
```
Code seems fine and the applet runs well otherwise. It seems like this is having issues finding the file:
```
multiload/src/main.c:513:    ui_path = g_build_filename (MULTILOAD_MENU_UI_DIR, "multiload-applet-menu.xml", NULL);
```
Is the error in how I'm building or is something missing in this PR?

**Comment by vkareh** [comment]
The error I posted above leads to this:

This is the context menu in `master`:
multiload-master

This is the context menu in `pull/549`:
multiload-549

**Comment by rbuj** [comment]
@vkareh done

**Review by raveit65 — APPROVED** [review]
LGTM,
builds and runs same like before.

**Pull request merged**
