### PR TITLE
NetspeedApplet subclass of MatePanelApplet

### PR DESCRIPTION
**Pull request by rbuj**
- Requires mate-panel 1.25.2

### CODE REVIEW

**Review by vkareh — APPROVED** [review]
LGTM

**Comment by rbuj** [comment]
WIP: there is a segfault after removing it from panel
```
free(): invalid pointer
```

**Comment by vkareh** [comment]
Oh wow, good catch. I had not noticed that

**Review by lukefromdc — COMMENTED** [review]
Build completes and applet works. We get these incompatable pointer build warnings however as of where this stands now:

```
  CC       netspeed.o
In file included from /usr/include/glib-2.0/glib/glist.h:32,
                 from /usr/include/glib-2.0/glib/ghash.h:33,
                 from /usr/include/glib-2.0/glib.h:50,
                 from /usr/include/gtk-3.0/gdk/gdkconfig.h:8,
                 from /usr/include/gtk-3.0/gdk/gdk.h:30,
                 from /usr/include/gtk-3.0/gtk/gtk.h:30,
                 from netspeed.c:27:
netspeed.c: In function ‘netspeed_applet_finalize’:
/usr/include/glib-2.0/glib/gmem.h:122:18: warning: passing argument 1 of ‘gtk_widget_destroy’ from incompatible pointer type [-Wincompatible-pointer-types]
  122 |       (destroy) (_ptr);                                  \
      |                  ^~~~
      |                  |
      |                  GtkDialog * {aka struct _GtkDialog *}
netspeed.c:1513:5: note: in expansion of macro ‘g_clear_pointer’
 1513 |     g_clear_pointer (&netspeed->details, gtk_widget_destroy);
      |     ^~~~~~~~~~~~~~~
In file included from /usr/include/gtk-3.0/gtk/gtkapplication.h:27,
                 from /usr/include/gtk-3.0/gtk/gtkwindow.h:33,
                 from /usr/include/gtk-3.0/gtk/gtkdialog.h:32,
                 from /usr/include/gtk-3.0/gtk/gtkaboutdialog.h:30,
                 from /usr/include/gtk-3.0/gtk/gtk.h:31,
                 from netspeed.c:27:
/usr/include/gtk-3.0/gtk/gtkwidget.h:619:50: note: expected ‘GtkWidget *’ {aka ‘struct _GtkWidget *’} but argument is of type ‘GtkDialog *’ {aka ‘struct _GtkDialog *’}
  619 | void    gtk_widget_destroy    (GtkWidget        *widget);
      |                                ~~~~~~~~~~~~~~~~~~^~~~~~
In file included from /usr/include/glib-2.0/glib/glist.h:32,
                 from /usr/include/glib-2.0/glib/ghash.h:33,
                 from /usr/include/glib-2.0/glib.h:50,
                 from /usr/include/gtk-3.0/gdk/gdkconfig.h:8,
                 from /usr/include/gtk-3.0/gdk/gdk.h:30,
                 from /usr/include/gtk-3.0/gtk/gtk.h:30,
                 from netspeed.c:27:
/usr/include/glib-2.0/glib/gmem.h:122:18: warning: passing argument 1 of ‘gtk_widget_destroy’ from incompatible pointer type [-Wincompatible-pointer-types]
  122 |       (destroy) (_ptr);                                  \
      |                  ^~~~
      |                  |
      |                  GtkDialog * {aka struct _GtkDialog *}
netspeed.c:1514:5: note: in expansion of macro ‘g_clear_pointer’
 1514 |     g_clear_pointer (&netspeed->settings, gtk_widget_destroy);
      |     ^~~~~~~~~~~~~~~
In file included from /usr/include/gtk-3.0/gtk/gtkapplication.h:27,
                 from /usr/include/gtk-3.0/gtk/gtkwindow.h:33,
                 from /usr/include/gtk-3.0/gtk/gtkdialog.h:32,
                 from /usr/include/gtk-3.0/gtk/gtkaboutdialog.h:30,
                 from /usr/include/gtk-3.0/gtk/gtk.h:31,
                 from netspeed.c:27:
/usr/include/gtk-3.0/gtk/gtkwidget.h:619:50: note: expected ‘GtkWidget *’ {aka ‘struct _GtkWidget *’} but argument is of type ‘GtkDialog *’ {aka ‘struct _GtkDialog *’}
  619 | void    gtk_widget_destroy    (GtkWidget        *widget);
      |                                ~~~~~~~~~~~~~~~~~~^~~~~~
netspeed.c: In function ‘netspeed_applet_class_init’:
/usr/include/gtk-3.0/gtk/gtkwidget.h:59:36: warning: initialization of ‘GObjectClass *’ {aka ‘struct _GObjectClass *’} from incompatible pointer type ‘GtkWidgetClass *’ {aka ‘struct _GtkWidgetClass *’} [-Wincompatible-pointer-types]
   59 | #define GTK_WIDGET_CLASS(klass)    (G_TYPE_CHECK_CLASS_CAST ((klass), GTK_TYPE_WIDGET, GtkWidgetClass))
      | 
```

That said, this will be a nice code cleanup when it is done: neater and more organized

**Comment by rbuj** [comment]
@lukefromdc done

**Review by lukefromdc — APPROVED** [review]
The incompatable pointer warnings are now gone, and we only get deprecation warnings now with my usual build options. Applet works fine when installed, as before

**Comment by lukefromdc** [comment]
The Travis failure are unrelated to this PR:
a bad mate-panel-1.25.2.tar.xz tarball with Debian (cannot be untarred), and hitting a rate limiter on Fedora.

**Comment by raveit65** [comment]
> a bad mate-panel-1.25.2.tar.xz tarball with Debian

@lukefromdc 
Again, this isn't a bad tarball. This is an issue with ubuntu OS at travis or with xz package from ubuntu.
As core team member you should be able to restart the travis build, there is a button for it ;)
I see that issue very often and restarting helps always.

**Comment by lukefromdc** [comment]
I wasn't thinking a bad tarball sent to a distro, but rather a corrupted file either on their seever from interrupted transmission to them (since the happens w same.distro a lot) or a similar partial download from the distro on the Travis end.

**Pull request merged**
