### PR TITLE
I18n tooltip text: nothing to mount

### PR DESCRIPTION
**Pull request by rbuj**
Before:

before

After:

after

### CODE REVIEW

**Comment by monsta** [comment]
@rbuj: I could have missed it, but is `matelocaledir` variable actually used in any `Makefile.am`? I only found `MATELOCALEDIR` being used in the netspeed applet.

**Comment by rbuj** [comment]
`DATADIRNAME` has been removed from gettext 0.20. 

https://github.com/coreutils/gnulib/commit/46133252579ffd78438ebaa2761ec19ecd1e1297#diff-7b950a0fa3c34d0aa7044293296b3126L364-L366

**Comment by monsta** [comment]
No, I meant the actual usage of `matelocaledir` variable...

**Comment by rbuj** [comment]
If the somethinglocaldir variable is set, such as setting matelocaledir, it will be used for setting where to install the translation files.

**Comment by monsta** [comment]
I thought it was set via `MATELOCALEDIR`? Also `-DMATELOCALEDIR` should be used in `Makefile.am`, and `bindtextdomain` should be called in the code?

**Comment by monsta** [comment]
Ok, let's see what happens if we drop that... in #445.

**Pull request merged**
