### PR TITLE
stickynotes: create parent dir for "stickynotes-applet.xml" if it doe…

### PR DESCRIPTION
**Pull request by oliver-joos**
…s not exist. Fixes issue #254

### CODE REVIEW

**Comment by raveit65** [comment]
Thank you
Works well.

**Comment by muktupavels** [comment]
String from g_path_get_dirname should be freed...

**Comment by raveit65** [comment]
Done!
https://github.com/mate-desktop/mate-applets/commit/dcd2ca4aa5ba43b7402fd468153f6ddccd74219c

**Comment by oliver-joos** [comment]
Thanks for merging (and fixing) my fix so quick!

Is there a chance that it will be backported to MATE 1.18?

**Comment by raveit65** [comment]
Sure as it is a bug fix....... and done!

**Pull request merged**
