### PR TITLE
netspeed: remove warning about g_object_disconnect on remove it from panel

### PR DESCRIPTION
**Pull request by rbuj**

### CODE REVIEW

**Comment by raveit65** [comment]
@rbuj 
another file conflict.

**Comment by rbuj** [comment]
The merge conflict has been fixed.

**Comment by raveit65** [comment]
When/Where do you see a warning when removing the applet from panel?
I like to reproduce the issue but i don't see the warning in terminal.
```
[rave@mother ~]$ /usr/libexec/mate-applets/mate-netspeed-applet 

```

**Comment by rbuj** [comment]
@raveit65 Steps to reproduce:

1. Launch mate-netspeed-applet from a terminal
2. Add Netspeed applet to a panel
3. Remove Netspeed applet from the panel

Screenshot at 2020-07-20 10-05-56

**Comment by raveit65** [comment]
Warning confirmed,
first i used `mate-panel-test-applets` in a second terminal for testing.
With that test-setup i couldnt trigger the warning.
Anyway, i can't test this with a rpm in the moment, because of
```
+ /usr/bin/cat /builddir/build/SOURCES/mate-applets_0001-netspeed-fix-memory-leaks-on-backend.patch
+ /usr/bin/patch -p1 -s --fuzz=0 --no-backup-if-mismatch
+ /usr/bin/cat /builddir/build/SOURCES/mate-applets_0001-netspeed-remove-warning-about-g_object_disconnect-on.patch
+ /usr/bin/patch -p1 -s --fuzz=0 --no-backup-if-mismatch
1 out of 10 hunks FAILED -- saving rejects to file netspeed/src/netspeed.c.rej
error: Bad exit status from /var/tmp/rpm-tmp.re1ilw (%prep)
```
First we need to finish https://github.com/mate-desktop/mate-applets/pull/476 first.

**Comment by raveit65** [comment]
Those warnings we have since https://github.com/mate-desktop/mate-applets/pull/475
```
[root@mother rave]# dmesg | grep netlink
[    0.431692] audit: initializing netlink subsys (disabled)
[    1.184576] Initializing XFRM netlink socket
[37392.464527] netlink: 'mate-netspeed-a': attribute type 6 has an invalid length.
[37393.466415] netlink: 'mate-netspeed-a': attribute type 6 has an invalid length.
[37394.468087] netlink: 'mate-netspeed-a': attribute type 6 has an invalid length.
...
....
```
I don't think that they caused your segfaults.
But i didn't test this PR yet.

**Comment by raveit65** [comment]
@lukefromdc 
In terminal do 
```
[rave@mother ~]$ gdb /usr/libexec/mate-applets/mate-netspeed-applet 
```
Than load the applet to a panel.

**Comment by rbuj** [comment]
@lukefromdc the kernel warning is triggered because of the third message sent, I'll try to fix it

```C
    /* Get in/out bitrate/rate/total, siganl quality from station message */
    msg = nlmsg_alloc ();
    if (!msg) {
        g_warning ("failed to allocate netlink message");
        goto cleanup;
    }
    genlmsg_put (msg, 0, 0, nlstate.nl80211_id, 0, NLM_F_DUMP, NL80211_CMD_GET_STATION, 0);
    /* Add message attribute, which interface to use */
    nla_put (msg, NL80211_ATTR_MAC, ETH_ALEN, devinfo->station_mac_addr);
    nla_put_u32 (msg, NL80211_ATTR_IFINDEX, devidx);
    /* Add the callback */
    nl_socket_modify_cb (nlstate.sock, NL_CB_VALID, NL_CB_CUSTOM, station_cb, devinfo);
    /* Send the message */
    ret = nl_send_auto (nlstate.sock, msg);
    g_debug ("NL80211_CMD_GET_STATION sent %d bytes to the kernel", ret);
    /* Retrieve the kernel's answer */
    ret = nl_recvmsgs_default (nlstate.sock);
    nlmsg_free (msg);
    if (ret < 0) {
        g_warning ("failed to recive netlink message");
    }
```

**Comment by rbuj** [comment]
@lukefromdc #510 should remove the kernel warning from logs

**Comment by raveit65** [comment]
@rbuj 
Opps, can you please do a rebase?
There is a conflict with master.

**Comment by rbuj** [comment]
@raveit65 done

**Pull request merged**
