### PR TITLE
require GTK+ 3.22 and GLib 2.50

### PR DESCRIPTION
**Pull request by monsta**

### CODE REVIEW

**Comment by raveit65** [comment]
rebased for fixing a merge conflict after latest commit.

**Comment by lukefromdc** [comment]
Should I go ahead and merge this?

**Comment by raveit65** [comment]
@lukefromdc 
sec, i will do ,  i am just testing the commit and start with tarball creation.
Do you like to have access to https://pre-release.mate-desktop.org/ for testing tarballs?

**Comment by lukefromdc** [comment]
Sure, I may not be able to get to all of them but I can pull core packages from there for testing. Will reportback results on all tests

**Comment by lukefromdc** [comment]
How much do the released tarballs differ in content from pulling git master, making a copy of the entire local directory, using git log to generate the changelog within it, then removing the git directory and making a tar.xz tarball of the whole thing? That's how I normally store source tarballs of every debian package I build?

**Comment by raveit65** [comment]
I send access data to your email.
At least all tarball are state of master and created with distcheck. It's more a last QA check for confirming that the distcheck process was fine or i did an error on the last inch.
You never none.....
Thanks

**Comment by raveit65** [comment]
All tarball i create with
./autogen.sh && make && make distcheck

**Pull request merged**
