### PR TITLE
build: make maintainer-clean

### PR DESCRIPTION
**Pull request by rbuj**
Test:
```
$ ./autogen.sh --prefix=/usr && make && make distcheck && make maintainer-clean
$ git status
```

### CODE REVIEW

**Comment by raveit65** [comment]
po files and m4 folder are still there after `make maintainer-clean`, but all other files are removed.
```
[rave@mother mate-applets-dist]$ git status
On branch MAINTAINERCLEANFILES
Your branch and 'origin/MAINTAINERCLEANFILES' have diverged,
and have 2 and 1 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   ChangeLog
	modified:   po/af.po
	modified:   po/am.po
<cut>
	modified:   po/zh_TW.po
	modified:   po/zu.po

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	m4/codeset.m4
	m4/extern-inline.m4
<cut>
	m4/xsize.m4
	mate-applets-1.25.1.tar.xz

no changes added to commit (use "git add" and/or "git commit -a")
[rave@mother mate-applets-dist]$ 
```
Is that intend?

**Comment by rbuj** [comment]
```diff
71c71
< EXTRA_DIST = \
---
> M4_FILES = \
72a73,76
> 	m4/as-ac-expand.m4
> 
> EXTRA_DIST = \
> 	$(M4_FILES) \
109a114
> 	$(filter-out $(M4_FILES), $(wildcard m4/*.m4)) \
```

**Comment by rbuj** [comment]
Now it delete the copied m4 files. The m4 folder cannot be deleted as there are 2 files in the git repo.
The po files are tracked in the git repo, so you can undo the changes by doing `git checkout -- po/*.po`

**Review by raveit65 — APPROVED** [review]
Works as expected.

**Pull request merged**
