### PR TITLE
deprecated gtk show uri

### PR DESCRIPTION
**Pull request by raveit65**
Please test.

### CODE REVIEW

**Comment by raveit65** [comment]
For the weather applet from master you need libmateweather 1.19.1, i bumped up version requirement for mate-applets. https://github.com/mate-desktop/mate-applets/commit/8111ccc52917dd0de924920b333a37240674dd9b
This was needed for fixing https://github.com/mate-desktop/mate-applets/issues/231

**Comment by lukefromdc** [comment]
Thought I had built that, but just found there was a problem with it

**Comment by monsta** [comment]
Shouldn't https://github.com/mate-desktop/mate-applets/commit/3d77c091475841c891785bcb8b2063f6801d36fd be reverted?

**Comment by raveit65** [comment]
opps, sorry, yes,......to much PRs and commits in my head.

**Comment by raveit65** [comment]
...and done!

**Comment by monsta** [comment]
Thanks 🙂

**Comment by lukefromdc** [comment]
The documentation for gtk_show_uri_on_window and the deprecation note seem to have disappeared from the GTK3 documentation 
https://developer.gnome.org/gtk3/3.22/gtk3-Filesystem-utilities.html#gtk-show-uri
but can still be found in the GTK4 documentation at 
https://developer.gnome.org/gtk4/3.91/gtk4-Filesystem-utilities.html#gtk-show-uri-on-window

I am wondering if that's just a website bug (older version shown) or something more?

**Comment by monsta** [comment]
Probably was some issue on their side - I see that function there now

**Pull request closed without merging**
