### PR TITLE
geyes: Avoid memory leak

### PR DESCRIPTION
**Pull request by shlyakpavel**

### CODE REVIEW

**Comment by rbuj** [comment]
You can add `g_free (file_name);` at
https://github.com/mate-desktop/mate-applets/blob/2b8aed048801103f93692c325f47b2402cc9abf6/geyes/themes.c#L122

and remove the lines:
https://github.com/mate-desktop/mate-applets/blob/2b8aed048801103f93692c325f47b2402cc9abf6/geyes/themes.c#L137
https://github.com/mate-desktop/mate-applets/blob/2b8aed048801103f93692c325f47b2402cc9abf6/geyes/themes.c#L158

I recommend to change PR title to: `geyes: Avoid memory leak`

**Comment by shlyakpavel** [comment]
Just like this?

**Comment by muktupavels** [comment]
I would just call `g_free` after first `fopen`:
```
file_name = g_strdup_printf("%s%s",theme_dir,"/config");
theme_file = fopen (file_name, "r");
g_free (file_name);
```

And inside `if (theme_file == NULL)` you can just do:
```
theme_file = fopen (GEYES_THEMES_DIR "Default-tiny/config", "r");
```

**Comment by shlyakpavel** [comment]
@muktupavels like this?

**Comment by muktupavels** [comment]
Yes, but better wait for comments/reviews from MATE developers (I am not!).

If others agree with my proposal then you will need to squash commits into one - there is no need for two separate commits in this case. Also there is indentation/style problem with newly added `g_free` line. And remove extra empty line where you removed `g_free` line. And above `if it's still NULL we've got a major problem` comment you probably need to restore empty line.

**Comment by rbuj** [comment]
> If others agree with my proposal then you will need to squash commits into one - there is no need for two separate commits in this case. Also there is indentation/style problem with newly added `g_free` line. And remove extra empty line where you removed `g_free` line. And above `if it's still NULL we've got a major problem` comment you probably need to restore empty line.

@muktupavels, I agree with all your suggestions. Let's see what others think.

**Comment by rbuj** [comment]
Another approah:
```C
static void
parse_theme_file (EyesApplet *eyes_applet, FILE *theme_file)
{
        gchar line_buf [512]; /* prolly overkill */
        gchar *token;

        if (fgets (line_buf, 512, theme_file) == NULL)
               printf("fgets error\n");

        while (!feof (theme_file)) {
                token = strtok (line_buf, "=");
                if (strncmp (token, "wall-thickness",
                             strlen ("wall-thickness")) == 0) {
                        token += strlen ("wall-thickness");
                        while (!isdigit (*token)) {
                                token++;
                        }
                        sscanf (token, "%d", &eyes_applet->wall_thickness);
                } else if (strncmp (token, "num-eyes", strlen ("num-eyes")) == 0) {
                        token += strlen ("num-eyes");
                        while (!isdigit (*token)) {
                                token++;
                        }
                        sscanf (token, "%d", &eyes_applet->num_eyes);
			if (eyes_applet->num_eyes > MAX_EYES)
				eyes_applet->num_eyes = MAX_EYES;
                } else if (strncmp (token, "eye-pixmap", strlen ("eye-pixmap")) == 0) {
                        token = strtok (NULL, "\"");
                        token = strtok (NULL, "\"");
                        if (eyes_applet->eye_filename != NULL)
                                g_free (eyes_applet->eye_filename);
                        eyes_applet->eye_filename = g_build_filename (eyes_applet->theme_dir,
                                                                      token,
                                                                      NULL);
                } else if (strncmp (token, "pupil-pixmap", strlen ("pupil-pixmap")) == 0) {
                        token = strtok (NULL, "\"");
                        token = strtok (NULL, "\"");
                        if (eyes_applet->pupil_filename != NULL)
                                 g_free (eyes_applet->pupil_filename);
                        eyes_applet->pupil_filename = g_build_filename (eyes_applet->theme_dir,
                                                                        token,
                                                                        NULL);
                }
                if (fgets (line_buf, 512, theme_file) == NULL)
                        printf("fgets error\n");
        }
}

int
load_theme (EyesApplet *eyes_applet, const gchar *theme_dir)
{
	GtkWidget *dialog;

	FILE* theme_file;
        g_autofree gchar *file_name = NULL;

        file_name = g_build_filename (theme_dir, "config", NULL);
        theme_file = fopen (file_name, "r");
        if (theme_file == NULL) {
                file_name = g_build_filename (GEYES_THEMES_DIR "Default-tiny", "config", NULL);
                theme_file = fopen (file_name, "r");
        }

	/* if it's still NULL we've got a major problem */
	if (theme_file == NULL) {
		dialog = gtk_message_dialog_new_with_markup (NULL,
				GTK_DIALOG_DESTROY_WITH_PARENT,
				GTK_MESSAGE_ERROR,
				GTK_BUTTONS_OK,
				"<b>%s</b>\n\n%s",
				_("Can not launch the eyes applet."),
				_("There was a fatal error while trying to load the theme."));

		gtk_dialog_run (GTK_DIALOG (dialog));
		gtk_widget_destroy (dialog);

		gtk_widget_destroy (GTK_WIDGET (eyes_applet->applet));

		return FALSE;
	}

        eyes_applet->theme_dir = g_path_get_dirname (file_name);
        parse_theme_file (eyes_applet, theme_file);
        fclose (theme_file);

        eyes_applet->theme_name = g_path_get_basename (eyes_applet->theme_dir);
        eyes_applet->eye_image = gdk_pixbuf_new_from_file (eyes_applet->eye_filename, NULL);
        eyes_applet->pupil_image = gdk_pixbuf_new_from_file (eyes_applet->pupil_filename, NULL);
	eyes_applet->eye_height = gdk_pixbuf_get_height (eyes_applet->eye_image);
        eyes_applet->eye_width = gdk_pixbuf_get_width (eyes_applet->eye_image);
        eyes_applet->pupil_height = gdk_pixbuf_get_height (eyes_applet->pupil_image);
        eyes_applet->pupil_width = gdk_pixbuf_get_width (eyes_applet->pupil_image);

	return TRUE;
}
```

**Comment by raveit65** [comment]
@shlyakpavel 
Any chance of rewording `Update themes.c` commit, please?
Something like `geyes: short-description-what-commit-does`.
I mean an update can be everything and isn't meaningful if you browse through git history.

**Comment by raveit65** [comment]
@shlyakpavel 
Btw. both commits can be squashed in one, or not?

**Comment by shlyakpavel** [comment]
Done

**Comment by raveit65** [comment]
@rbuj 
Are you fine with PR and can approve it?

**Comment by rbuj** [comment]
Yes, it's ready to go.

**Pull request merged**
